title: "Il mio sito Jekyll"
description: "Benvenuti nel mio sito Jekyll ospitato su GitHub Pages."
baseurl: ""
url: "https://tuo-utente.github.io"
theme: "minima"  # Puoi scegliere un altro tema tra quelli di GitHub Pages
